### ISSUE TITLE
Stuttering when triggering GCD. 2.11.5

### ISSUE THREAD

**Issue by Calzeru** [WeakAuras/WeakAuras2#1197]
**Describe the bug**
Stuttering when triggering gcd.

**Do you have an error log of what happened?**
No errors.

**To Reproduce**
Trigger a gcd.

**Screenshots**
https://www.youtube.com/watch?v=eQza4i9iEBo

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, it still happens with only WA enabled.

**Which version of WeakAuras are you using?**
2.11.5

**Was it working in a previous version? If yes, which was the last good one?**
No issues with 2.11.3. Haven't tried 2.11.4.

**Additional context**

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/2888680/WeakAuras.zip)

**Comment by devil81** [comment]
I have same problem - IM Using Afenar | Demon Hunter v1.0.3-47 and it was all good but now even when i walk in game i get stutter/freez for 1 sec every 3sec

**Comment by cirquedecarnage** [comment]
Same error. Turned back 2.11.3 and no problem. I get fps stutter when i'm in combat (because of wa's activated on combat). Obviously latest update (2.11.5) has a problem.

**Comment by ronoudgenoeg** [comment]
Same issue here. 2.11.5 reduces my FPS in-combat by quite a lot.

**Comment by InfusOnWoW** [comment]
Commenting that you have the same issue, without including your settings is pointless as it adds nothing to the report.

**Comment by InfusOnWoW** [comment]
We merged something into the latest alpha. Since I couldn't really reproduce the issue, we'd love if you could try the latest alpha and see if that fixes the issue.

**Comment by devil81** [comment]
it is better when you are out of combat but in combat its realy bad

**Comment by emptyrivers** [comment]
If you could share your savedvariables file for WeakAuras, that would be very helpful. Also, to confirm, you are still experiencing this issue with the latest alpha version of WeakAuras?

**Comment by devil81** [comment]
Yes , before last update the problem was like on the video https://www.youtube.com/watch?v=eQza4i9iEBo 

After update i only have problems when combat starts ... 

[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/2895619/SavedVariables.zip)

**Comment by mrbuds** [comment]
You did not make it clear if you use ALPHA version or 2.11.5 as asked by Infus and Rivers

**Comment by devil81** [comment]
I use 2.11.5 ( last version )

**Comment by mrbuds** [comment]
Please use alpha version (2.11.5-1-g72951d3 right now) or 2.11.3
You can find alpha version here https://www.wowace.com/projects/weakauras-2/files

**Comment by ronoudgenoeg** [comment]
This alpha fixed the issue for me.

**Comment by InfusOnWoW** [comment]
@ronoudgenoeg thanks!
