### ISSUE TITLE
Player health trigger not updating properly

### ISSUE THREAD

**Issue by anerud** [WeakAuras/WeakAuras2#3554]
### Description

A simple progress bar with player health trigger is not updating properly.

Example on how to trigger: Change gear and you health goes down. Heal yourself and health does not go up.

Appeared after ZA prepatch in TBC Classic.

### WeakAuras Version

WeakAuras 3.7.14

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Change gear and your health goes down (as it should). 

Heal yourself and health should go up, but does not go up .

### Export String

!WA:2!nAvZVXrsv8z2bK3yKq2taZsioRxdXKaXJhpooXjqW70JhNzcoJ92Z4njOvA6Q7UMURKE6QuvDp(JB7WEiNhHqAVHMdioWb0CeHeRS2dCSKHlC1NqieiL)aaEv19ApjoSH(q)XRF179Qx97379YUz(U5DZ7(87muWq8N9iIBK)3CiXHg2KgZDWxoJ9EipA9ngWwCVk0kOIRY3F7oDe4OSdDIfr0UTW7h9w8dse(h(kJqHo(u(ousyKDLQnAv1KnT24M0iueHg(qQl2O8UT2(4xsCw2uNzWDzUOiSDS(rPyEa774hfXe3DPLuXtbcDPtdOLkXrokliULPicXJM0UdjKi8N0aEeTGDIzzBJI5O24WEf4ypq9c2iEHoE3Tjo6(CKlbhgDT5RTTz9F22nAvER5VXCfluCLBuSWnxfUTwj4wPIWTvxdUDNsxFGlTDIP977t88BrCXV9V8pPZETDObu(dYbxVaseyEik4dXCb4wVbOqsx9w(wY8BEegjWnJ44qVi)jmIoGHncPH4JDHOvPuBLiUadw1v0xPDlqG8kgDrKWnLxEc5SYRiFx5CY3dEEXxvsFyxwrhm1w)3nL(Q26)9d1x1w)Z)g6RCdDXcuKYJyFd1gWN3ljC)QdfX2M6eM4bZiN9y4tBKZZ8404q3ubDOqkvl45VllFeCa2w4JCP794eyrUbAzQB8R6Jrbr(SPgtTKamB2S5yx5unBdwfYtTt0p9l5vyF7ZPbl9LbgeVgXDTXC2371OKnXRDO(3PYyZu22MJ7rGT9wiUhozXItscnCqhnmwEb2f1sqXWHnCO4O5jgLHpFrIli7JD1c)y2398EgdmPWigDpWZAGH1XjSKNKsLosR(tbWePZbYlmKR4eyfrWOX2nQYM982uBStZjjjZXOEhvVrJQMTtiGjMVhrqSdWwYz5WrMse7AF5Xk60SJ)qTsNHQhKUiq1P2KtoCUpig5cWh0CTAXUX)VMTDx0(t)saM0mYLZC8Poqb35BVBRTQ3OAI09OC3hXrS(pk9f2sF5E8CN8YsVoeY4ljvVIVPCehqNDBhI6IndXaNH9EVgKxePlUnJJDikkvUZ2BnjhIVykyiLRK9nTzCbZ0ffmM9E(8YBBj)HSPV6YfsvnH0Cv5IaT)F9hvxF2R7L)2VVWVjtMmYB9XY7k)rSV)588RyWuX2jefzzF5pgk1S5LZiRlFGCDlwP3OfoF4l35IYpil7Q)V22Vsba5sYIYvKxqEt5QY1YkVd86SY3pfg9s5Y)rwzf5gYQtlnG8W)8FRU(pNppKtEFzn525K)GSYTaJVSSK8EJsyqM1VFTwYFki5HYgsZC2(yOwF0QhdfdahTnt35zsJakY9xFCSaoNXr2OOOaS)jobiHacj32cg2zbBbj0la)jtz2noiImZNmLLDeka2IZiTM0uR9cY22nRv(HLBiTMr6yXpeAgu3v8w9v2wzgRbQ30GnFTd7H9job4Dj(gA3iBpH06RBnHLHaGxktFIUtRb4jxv33sL3yd2uWsl7QQ5GDXUpeTV)rATsYCpoBFk4Ga0bIlPi81w)V(PF6NLjZAdgRSOn0OOdXBYKHhQCAXHteDP0i)D4upowiSEvFrc9hM0dwZTv9LHUuM7PkGUXxZefW8r7KRyHBpq3lvanwn1NdJhHpj78ex23QMgCm3IZzG4ZDTM(OUOWRpxPrAnRPpRUhxHmI5yZM0aIRTa3f2AMlxOyHLtSyRK)ZUwDvV6oih8hvbbfJd9aR(r7wFXZ(AXM6uPQvG1WiQtABY3EN3j1LexxCOzJQFyvtJdP0Uzh1HdvhGw8q1XjErc(CtLi1M3UzfZQvByQxRFPyI7ip61JU)D24Pp5XgCsOY(y)xCwl3t7vwB9)8kR8(zYKDeLRgErpTWWZgGzOAIbIgEEPfmD8XopBtEeN45H55MNYM)NCpZEOGy88RvSFpeNGGUdhnEPgUJpk0dlU0m9zCk8hyuK8qVJc3SW4Dugrct4MGRMH9oeVqyCGuIr1EGXQY5uUWQFQZfnwq(lE(09)IjCYV8rASTVAqarKLrmm2MndWEy(aDGOgbkBc56l(0cgzXoUthncQw1T2zZD3ckd8RgQ0kPIHppwXsaK6p3u)0obSyQQwlMSpqwccaQfqpIT1kSdhdTYnBUt1T26uHnbVq2Fu7kLB2QDZwLnBXMoHNpw1j)tuIq2ck3wrXS00v1gbORHPB8jh5sepnoeMwThUek8a20i97Ts(VAH)2m5f2Ru42fw(M579xE8)9p

**Comment by mrbuds** [comment]
That's already fixed in alpha.

**Comment by Mandalone** [comment]
Was writing the same report.

upadted version of Weauras didn't resolve the problem.

![Non Full Health](https://user-images.githubusercontent.com/102297609/159916570-0ffcb63f-be7c-49a3-9c36-25df55befe6d.PNG)

![Full Health](https://user-images.githubusercontent.com/102297609/159916610-1e815604-3d35-4e99-87dd-43f92fa7a06a.PNG)


The health seems to be update after the next calcul occurs. So it does not show the actual value, and if fully healed the bar doesn't update at all.

**Comment by anerud** [comment]
Any plan on releasedate for alpha into new version where this issue is fixed @mrbuds ? Or if you can point me to a branch/tag/commit and I can clone down the code myself and try.

**Comment by anerud** [comment]
Latest at master works (seems like d816e72) solves the problem.
