### ISSUE TITLE
Issue with Custom Texts

### ISSUE THREAD

**Issue by Sakatard** [WeakAuras/WeakAuras2#4243]
### Description

all my weakauras with custom code that use GetTime() are having issues with text displaying, this is the last commit where everything is working fine [c051113](https://github.com/WeakAuras/WeakAuras2/commit/c0511131858fb7882a123786c0da2bb2751a2d41) any commit past that renders this issue:
![WowClassic_JPfysoCA9F](https://user-images.githubusercontent.com/1248805/212780460-48f7b11a-5bfd-4fea-9234-b04680a05d39.png)

this is the correct behaviour:
![WowClassic_TwZQWX0W6m](https://user-images.githubusercontent.com/1248805/212780497-2ae94348-7c28-44f8-b742-a5ad20818388.png)

### WeakAuras Version

f01ba4a

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
no lua error
```

### Reproduction Steps

use any commit past c051113, use the exported string to test (but im assuming any weakaura with GetTime() in it will work)

### Last Good Version

c051113

### Export String

```true
!WA:2!nFvWUTTrqu74cKc2dnwOWOP5cJlCGKTtKSdQBrqCbSSLrCRCmHSCIsBdKxrUKATP2Ly3LkYPi9GqpKt9Gp0paDUN0xqq(cim6xq(eYxqhUKsHIIQfiNkbS1YzNz2zM9nVD587NRtoRCwVEfoZx6sOy(rNuV6bpUYviFzBg)ipjHrfAdTicpx0f1X9KlVI5atFHK1j8TEFYz2(uZq1YxqthECzMixDqshS(26H)mXecSqakVNphfAeOsELU3fbsAIPDVxSgfkE)TkvAAlBy0MdwLw9ggft56eM6I7IDtBySWIPxFlc1PWQJxC1)i26P0Y3ZcjX6FFYib1XdkIohqLyExyzLTX0rEqp5Grrf1r2gcPVESlAyKsNo(Usc4vCyOhgtfZpZ1B1ihwySlsfSMmFQmzfiP412yAZAy8Z5Zu5vIJ9cRTXZt6qt)oqadv)U4ezs2td2vkvY2WWfjKQDPstx0G9GmdMhoQqgwUhRD4ZefVeVS6ilkMPhh7dm1A6WWMX1jR3vNq1jEicxKpr9QGUftp1ZeHuIuC8W107otBYmesSGt4Pv)qoolmaOTciRL05CS0Nt1fsoGMUhKGDqY8ldTgT5pqFfX56)cv9cuHjIOMjL8jeh39PMy51TDzmE(jc0IBuQa8xP45g3tMsEI28rZuqlms10Us0gzXEXZoY2wGLZpernbskdgHkBTBLhxVsnVB8bQPtujCRO8(DaHgdslI5tjwY212N0dBXrkIlXw1esexQvMqjY70kYf9M)3tZX8b(SPRQPNqLEG8taxwnCC(LdzqX8LtOuhupvJqOsnmoe1llLmtOswZpzZDjTPzgNuCmOPKwAMWjfgsdMrEnDpS2SjabkRjwyqWV(knvh02BSU(wLG2fT0uoKNRCB0wU2LwSMrBiN2Yg2FeT16d4uhhmx8h3Hhp813yGfSvBBx)cpm)rvQAS)jvllHxcw89wxqrDiMJoxOn3Ncjmvwlm3Sk7dv2wrL1(wX6KBJAkvE7UTrs9dHcjYbxdCdgommkCAg69waWr6lAPuw4DBJQ78Sk1A2WO5jg7Tt9kRRhlPALNuPkimyXEx7rzEIzddlIT9yQpT0uEXaQmruts9n2tPXm63vpjQkIdWvG1N20uq0jneySMcoofFtsq1utoj4kjx0mbAZyI1IJzTzS4tjkBds2RKHWSn6FR9D6WzgKbtM0z3RNGKwY9XJ6n6l8WUUhyj0Qz2gBEEG(7e(ryrdo2M0R2XgvQwDSWJHgesVHn3DNJR38467uR(iSCBIf0PCjqHe1pTuWIBclq49(otbw7I3erVWlxm9AKwvzoeZEZpyw4zSRenE))Jglh7LpkWCSTFuO5PqK)NyKeSyQv()pOfVfrQnX4nUdzw4)AU3tc5PPi3NaCPqo8Qlfyx7OJtlFu96hDyzBgvE1((GVqalOfXVdVBKYl4DReFuqZOln00mEqzkJIl7Yqw)5L(cCtvkDAljcU4LCPAQ7PO9oL0MmGXgjz8CpSSG8s8sb7OXTJozgW1WnBeHIQPuE5VRuza0BQu6LWAaG)R1pmkpgm9MXxqOr8fegWXoGxcptOSeIYbqJqnLiXxTuaOTFRwiZZDGV(HA1)fmU1t5iV(pnEWatg1Ie9fqB6ZD9UvBP0t8GIfFbYHDpcR4psQUXZ(P7ZmkUb)IOf9rV530NtFU5Un)mOvHyFr5Qv2V(ajZmUW9PDFZYeRRIV5eCfKZXCEViJT(2H2C4qMJb5s0cVp6co7hkkmjAD8U1Qu5XB6tSgUj(OwFZbwy2Mh0cItBIduSyUm(pSa8mmQqSRsW8Zp)cdSdVWJ6Up79zdj0OTjiCUZqyOjUI6aSt9(sIdLXXXF4NsAfoNXfNEjIsImzRGp)jb3SLhhdHCFmsOcUGTFB4qi0v3T(6boLTrw4RgDKQ68sUahwufL7Gi09dUzW2bNh4gqUEqBy4xaUnWrneK4eCw4K5eBUhUBUU)DJ)5d
```

**Comment by InfusOnWoW** [comment]
That's has been already fixed.

**Comment by Sakatard** [comment]
the latest commit did not fix it, is there another commit you guys plan on pushing?

**Comment by lowpita** [comment]
Hey. There's a similar issue on retail (5.3.4-26-gf01ba4a) with custom text from auras like https://wago.io/B1tskRwHX/ where the text should only be displayed on mouseover (check conditions) and instead is displaying a %c1 text without mouseovering. Seems to be updated after opening wa options (/wa) or doing a reload, doesn't work everytime tho. Also happens with checking stacks (%s) text from item count, which displays %s instead of the actual item count. All those issues weren't happening in 5.3.4-21-g93ee75a4.
