### ISSUE TITLE
Condition tab does not handle changing of elements properly

### ISSUE THREAD

**Issue by Dsune0** [WeakAuras/WeakAuras2#4276]
### Description

the condition tab does not handle changing of elements properly, when a condition is changed or added the dropdowns are placed incorrectly and sometimes not interactable. See image below for example

![image](https://user-images.githubusercontent.com/106332935/214111223-7466377f-1656-499c-8b52-3f0f2e085a9b.png)

See gifs on link below for reproduction steps and result
https://imgur.com/a/vkxsHZd

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10482336/WeakAuras.zip)

### WeakAuras Version

WeakAuras 5.3.6

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Open or import the aura called "New"
2. go to the conditions tab
3. Create one condition
4. Choose "Any of"
5. add 3 different conditions for "Trigger Active"
6. Swap the top one of the "Trigger Active" to "Debuff Type" or similar condition which has more than one field

If it fails, try again :shr

### Export String

```true
!WA:2!1rvZUTTrqylOwyuwKwBfh3yxFiWf1afOWOWfXOi3mvPIDHIKdj9pf9h7LKdf3yQDz3DPKTVzDWiN1JGo3t6rWpblek6dqEe8tqNDLKBsbkpqoZ3mCM5B2z2knQ1TwsTK3(vJOXCwaVuedBSWesPkJlAxOOCM0rCv70ujOQmMWIr8d5uMkQUxRqp)jXCEEcVplOpTao)U5QEjDGmbj2gHD9LkIq54szuLtuk(rM5mqjOD6ac52BjMjE7OeiQmnn8QcqSVxZdBCutxfQ4tkfKDgilG88dsKoVtwgb9aMka9ME54ZQVxq4zbH75h6wIjjQiNCfiEWTdfa6MFWHEnB6BrI2hi5QmFgPliDgwYMvcoBPF0T6pt)56L0lRR5OFSEf9t0RQ)sh9A611FH(P6n(FDYy14f68goflB4FpiCAKFfpb(ZfUh7DGGrYpgzo2CU5(laOypKzXkFc2UYgkH8uBpw)Xy)qsui3vq2iKm(qhtd9fRQxAcQgrIVOJGxYsE7kf1uWLQZKzeS)F6StSI1SG2xPCrxc6WmbxgNbdFW8MFTSyP3lc155CXpvPsLQVBk68IYDVJcBx8ylioNWXqrJpHMOYC3dvVFAUOxcjwWBMmDO5NNvr3zT)MsPIMEfsqbxHKlebDB1ULNEjbYlJpJSogBlJQ4ZWzKGPkwQHGE9ZEDjjbBmKNfg(bCFEMMyX6ZfjNiifdozMW0cOhvsJYHZNX53BWUy5dA1YZ)m32HHTFL)bVC)WjpK6a61WAZy0PFqEmwTJTTpkS5bT8(7jDY59BiG)OeyXxD4h9DBVZZNYoJHXMxZJWaJI5NNevQuCw7EGaNFhzGBcSoQSNy9FoZgAuQ)qN5Usj8Y5izUgJzwxcIj5qvBHeMrJVGbszvRLMuuEzBcCX(ciYIYaANm1nU5Cssdxjs0v97wMROoUMHZv1V2XpoNiLgPifgzMYiosyNjnLVR5sKIvMFhG5q9hPsc2NtYexoNSZnF(qcJAME4SD1FsdCvAR7aIecuclNxCsIzWhnFM5kaHeWONihy8XKn9wUDjuM9h1)YI6Fv)B6Fhf)0)lI71CE3k(K8Ims1rkECVPREpTYTJ2KMStlOV))oNnovGxjGfboAv9(Ph1nmqMCgfu33ZRvewjP0oo7ustgFC6B8(b3EFtFHVGYmXgYkQHNj1NruCXh3SHZ97BxigzOb1EX46B5hNbXxSR(rF7cd6reutZAZ2(rwy5lW7zQQlCLz8(tf1I5FfXzewhqUUZykB6kngsh9XNxt6)8T)(T3TwV)60)j
```

**Comment by wazerstar** [comment]
Is this not the same as the one I just posted before you?

https://github.com/WeakAuras/WeakAuras2/issues/4274

**Comment by wazerstar** [comment]
I hope @InfusOnWoW see's both topic created and can fix it rather quickly at some point :)

**Comment by Dsune0** [comment]
I've been able to reproduce it consistently with this WA: https://wago.io/LNH9m0FJn
things i tried:
Fresh login -> open WA -> open custom condition -> close custom condition -> condition bricked
Reload -> open WA -> open custom condition -> close custom condition -> condition bricked
Logout and in again -> open WA -> open custom condition -> close custom condition -> condition bricked
Disable all addons except WA -> login-> open WA -> open custom condition -> close custom condition -> condition bricked

https://streamable.com/3pwkg7

Before opening custom condition
![image](https://github.com/WeakAuras/WeakAuras2/assets/106332935/190ed708-27c2-427f-b1e2-af47f5b81618)
After closing custom condition
![image](https://github.com/WeakAuras/WeakAuras2/assets/106332935/3f7cefb5-4ce1-4a74-b469-02c612ef9509)

**Comment by wazerstar** [comment]
Does not matter, they don't give shit about this issue, its 100% reproduce-able all the time when using conditions.

My post was before yours and "nuked" because of yours, does not make sense and this was like 6 months ago.

**Comment by InfusOnWoW** [comment]
@wazerstar That does not add anything to the ticket.

**Comment by wazerstar** [comment]
> @wazerstar That does not add anything to the ticket.

Sorry I'm just passionated about WA :/

**Comment by InfusOnWoW** [comment]
@Dsune0 Thanks that was at last a 100% reproducable way to get the bug and I think I've found a fix for it. So should be fixed in the next release.

**Comment by wazerstar** [comment]
> This should be fixed for the next release.

Has it been released yet? latest official release 5.5.6 does not fix it.

https://i.imgur.com/eZcV8LG.png

**Comment by InfusOnWoW** [comment]
The next release is not the current release, but the next one.
