### ISSUE TITLE
Improve Zone ID(s) (and similar) Load Condition inputs

### ISSUE THREAD

**Issue by ljosberinn** [WeakAuras/WeakAuras2#4616]
**Is your feature request related to a problem? Please describe.**
Any kind of aura with load conditions for e.g. multiple dungeons or encounters currently suffers from the issue that not only the field doesnt scroll to the right (given many ids), you also have to either note or simply remember which id matches to what, making it cumbersome to maintain.

The tooltip hovering the field already provides some utility making it more bearable, but it is not dynamic based on the already present ids.

![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/2b61f386-1a78-45f5-b943-1abc15a0c9ed)

**Describe the solution you'd like**
The Spell IDs trigger input list would be very handy for this scenario too:
![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/538295d0-2acd-45b6-91a6-a47cdd3a101d)

- per id, have an input
- provide name of the map/map group etc. if numeric and hint it similar to spell names in above screenshot

**Describe alternatives you've considered**

Extending the tooltip to be dynamic would probably also work but would likely only bloat the tooltip.

**Comment by mrbuds** [comment]
> suffers from the issue that not only the field doesnt scroll to the right (given many ids),

This was solved with https://github.com/WeakAuras/WeakAuras2/pull/4570

> per id, have an input

It was decided in #4570 to not do that

> provide name of the map/map group etc

[C_Map.GetMapInfo](https://mrbuds.github.io/wow-api-web/?search=api:function:GetMapInfo:MapUI) can return a name from a uiMapID
But I can't find a function that return a zone group name from a uiMapGroupID in [C_Map API ](https://mrbuds.github.io/wow-api-web/?search=api:system:MapUI:)

There will be same issue with encounter ids, we extract some of them from encounter journal but it's limited and i'd rather not maintain yet an other list of stuff stored in db2 game files but not accessible from API

**Comment by ljosberinn** [comment]
> This was solved with https://github.com/WeakAuras/WeakAuras2/pull/4570

The zone ID input still doesn't seem to have this behaviour, only Encounter ID, could that be? Zone ID behaviour is entirely unchanged as far as I can tell. Having overflowing content gets cut off and you can only navigate within the field by arrow keys left/right or selecting.

![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/65c43325-4e18-4239-a9c1-524b7bd98d31)

The reason why I filed this in the first place is that currently, due to how unwieldy _this input_ in particular is, I have to extract individual auras for each season because its too easy to lose track whether you've already added this zone or not:
![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/81fad798-dc7d-4edb-878c-757a60a82488)

I assume this is fairly niche but maybe some kind of validation could help? E.g. when entering `g432, g434, g431, g429, g282, 731, 936` and now adding _another_ `g434`, you get a hint saying `Duplicate id found: g434` or similar.

> But I can't find a function that return a zone group name from a uiMapGroupID in [C_Map API](https://mrbuds.github.io/wow-api-web/?search=api:system:MapUI:)

ah that's unfortunate...  each UiMapGroupMember "floor" has a UiMapID attached which yields the zone name but there's exceptions for eg. Dawn of the Infinites already

**Comment by InfusOnWoW** [comment]
#4570 is unreleased.
