### ISSUE TITLE
"Fade in" animation makes the element appear for a split second before actual fade kicks in

### ISSUE THREAD

**Issue by m0ndsoldat** [WeakAuras/WeakAuras2#4696]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Whenever I try to use the "fade in" animation (doesn't matter if preset or custom w/ variable settings), 
the fully opaque icon/bar/whatver appears and disappears for a split second and then, AFTER this, the proper fade in animation passes, making everything feel incredibly unsmooth and choppy. 

I've attached a video with a freshly made "Schism" icon aura with a 2s fade in time on the left side that should demonstrate the issue. 

https://github.com/WeakAuras/WeakAuras2/assets/150296353/bb00959c-da1b-4d2b-b0e8-bec97f83d861

Things I tried to troubleshoot so far:

Did not work:
- I logged onto a char I haven't played in a long time, disabled ALL addons except for the weakauras modules and I created a brand new icon aura for testing purposes. Issue persists.

**Did** seemingly work:
- Logged in on a starter edition account to try with a complete set of fresh Weakauras savedvariables (So I didn't have to mess with those in my mainaccount folder) and voilá, issue does not occur.

I remember having this issue since at least the beginning of Shadowlands.

I'm currently sitting at around ~1600 auras with a ~14mb Weakauras.lua filesize, if this is of any matter. 

Below is my zipped WeakAuras.lua
[WeakAurasLUA.zip](https://github.com/WeakAuras/WeakAuras2/files/13301532/WeakAurasLUA.zip)

### WeakAuras Version

WeakAuras 5.8.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
no errors
```

### Reproduction Steps

1. Create any Weakaura.
2. Attach a fade-in animation to it (custom or preset).
3. Observe behaviour.

**Comment by InfusOnWoW** [comment]
This is actually already fixed in a branch that we'll merge in the "near" future, though it'll probably be a few weeks until it ends up in a release.

**Comment by m0ndsoldat** [comment]
That's fantastic to hear. I honestly don't care too much when this is gonna end up in a release, just glad that it's not on my end somehow and that this has already been resolved. 

Thanks for the reply!

**Comment by calfmu** [comment]
Hi, I recently found out about this as well. I still have this problem so I assume the fix is not out yet?
For my own weakaura I added this line of code to animation.lua and it seems to work okay:
![Screenshot 2023-12-09 224601](https://github.com/WeakAuras/WeakAuras2/assets/62796294/fa91f34e-0ed0-44ae-9275-40e6f6d9e0a0)

**Comment by InfusOnWoW** [comment]
This is now merged for the next release.
