### ISSUE TITLE
Fyr'alath the Dreamrender weak aura isn't loading unless i'm not gcd locked? It loaded regardless of gcd previously, but now it only loads if not mid gcd. 

### ISSUE THREAD

**Issue by Keksecute** [WeakAuras/WeakAuras2#4923]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Fyr'alath the Dreamrender weak aura isn't loading unless i'm not gcd locked? It loaded regardless of gcd previously, but now it only loads if not mid gcd. 

https://wago.io/96RlGD8iU

### WeakAuras Version

5.12.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Opened weak aura settings, checked the load settings for the item.
2. tested in combat, still not loading.

### Last Good Version

yes, 5.11.3

### Screenshots

Can't SS to show why it isn't working in combat. but maybe this helps?

![image](https://github.com/WeakAuras/WeakAuras2/assets/48346057/cedc7caa-0796-45b5-9496-aaec580e17d2)

### Export String

```Text
!WA:2!Dzv3UnUnw4nJNff1flWeVDsZmTxymOn7pxKjoDNGIcuuyLypJxeBNi70m7vwus0sSrIKHKkjEUB9n7auSOy9JGFdQFeYtaHqFc8f9bipb7HuYozAaI1HKhE(97CoCJ21sRfwl89F)Cf(g1(NWiuL)HT6nSL7CsaJoGLjcWvYnN2OnJQgqEh(zIB6pESeR(IpwmPGk5Xlq0GyMWkb9J2ptKW)8yLIl)2x(YRrrSDjSx6o5hUS7E8V5Ox2qGcuegvEGRuHeQQoekrv1Fm8rgx9wR(Arr(j4qV7UaJ5nLCCGYfb3kEMeNmUutZdXsKktGu4yRt0WEWcN(dh2VRBNx)MHlT(MX6BNGIKI(Nn84o9A5KWqHV)ZeeAKGLX3YnnlrrQoltIhrXxHfXUbjiPChFjWscwCEtx3o9D1BxWJ9qp(tm0HcWfPcsiWz8DMDikCk(Ymchhgp1SHX(9eVJrXDcLpsOqjyQA)TaPT0kPriAOLPD0F(pR3ER)NNFbpgwCKqCVGOGJ)OHgcI2n51wBpRLI38qY4XKaWNMy4zXdmONVDLD45M7CfoMeKGpJepJFf)E9jgxKFm0ZTcNL6JuE8NTY3g5ZOzss4iRmnEPJGLuyoMqsZWFmtQWH4WUeA8Cboce3WjCSJbxLVoLyaunCTlFXxXDqzkM3CflaI)s4gBVX)HArd7xIgI9HRpMevDrirYtqt6aR3(GO)RVbL15OzRbz5bmwsi7A6GRbNgsubGbXshcc7mEiGx8ZSFUDfFTcJWXtvcsueO8D3rus((Nn14X9qPytGBgcqBuyH855TsMijiA9UKOyLaKrFAYeV8imflibdIzx3NUqA)4IrHtSiHmaQ7TWIjGtIcc9wkZ8behvDIapMCJ7GtAD8Xog(8nUiwmdsPjjglqDHRv3vDu2GjyyfPFKVKj8FdgL0LfIVxKdYayWnlgDyZbdhnyyt3HZxP6(uVL3Fv71CT3HV9HLXK6NiyrcSuw)V2bu1FBAOPudsm1AKlaDnyLDDRlo4IeGrk8FEjGV4iVPwsa2x92vWh7(8nnl)GGLNiJAnb9bc4qlBqjUp4egWJ4nTo(K2ND8SmAzYP6oANR0N6Ask7RdeVPPBxGb9rpF5HSeMuMjRpifjJ1T9YtrQGySSqv5fHGUePP(w77P7cvCIiSsJlLQESURUhil)MxHGZ0e9pcYXWBGoeyJVPPo5k8WcJXecRCh0(blOOKFOac)Zl5LXWIUP)9V4p8Ozikj1ghpq)jT1N6qH(c3Irs8aLatJuXFu(Qi9itIwiXaopuo1WJjsOV0jfrOWD1xQfFKwQv6mG8p973zPurcUyYrLslwuwzvzoGqCTLLYVDl9P5WsFuWfMMH0W3)P8AMYoaNGaCWBlAZVb)z2nT)mMjaxyKSKqF5S1N9IVsYFYdUUjti(NBSXgvwwS7Q(3onpByF(F2UPP03etcoNeQIDAclVRqrKBWH2n)35ftz(xLMJTZWitJgY4jWSabtbf0MkCNE971sFQaCkdp2jdqtmJzub(BwPhaq9N0wqEx9tZqqpCfQ(WHFGJVst2gwJUMjcpxG4tpVKiFTCS5KNw61pywiFZo961YD0dMhD)LSttl9P3(b(0vejbA3f)B5rjSRBlGUSyAWKtE8E7U)Rk8lZblm)S6Mtnlm2rUFMsXO9Hmn09yUz7JTGQNA5FLpnZS4W1XKBnlxbtQyQuF9QZJTSoiaMpuXXq6znRHWWJlm17vSNFmbO30Qohi(adq9JXMgJF3VFIa6MyOLJPyWNKYzII8tJ7TLINJC)6CaCaXO(C7JgGHz0cqhSANfazaULPPbmoEBseLjWLCA3TLqWesp37t)lx)Eg7lcwL3afsvqrvkCj)o9g05Ow2jtna8S(R9kyQXdys)lZwpit)t(sCkeYDBS7E7UNZ7yS0nEbjK)LTNi(lOeKkUUkgx)iOTzkuJdXN6irQSoLvpq6ETbF)DlglGoEqpaak(X3vamAB2YKw9hCOBRw9ST7x1Fg64aVjc7nBThP)j4fnMACC8(zKWf4b9CdAC9)4vUVM)PRg1zkroIilMOo30zHuezNUIJyxucpgvPM0)v72y)D3R2v)6B))p


https://wago.io/96RlGD8iU
```

**Comment by Keksecute** [comment]
So I tested the "Show global cooldown" checkbox and it seems to work, but that seems backwards compared to how it worked before.

**Comment by InfusOnWoW** [comment]
Can you create a minimal example? And better describe what exactly the behaviour is.

**Comment by InfusOnWoW** [comment]
Probably fixed with the other fixes, if not you have to provide additional information.

**Comment by Keksecute** [comment]
> Can you create a minimal example? And better describe what exactly the behaviour is.

It is still not working as it was before the patch. How better could I show what's happening? The weapon cannot be used during a gcd, but the trigger is cooldown progress, is that the incorrect trigger for checking if it's on cd or not? I would think checking "Show global cooldown" would show the gcd activating, or when it's available after gcd?

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/4938 is probably the same issue and a far better description of the problem.

**Comment by Keksecute** [comment]
> https://github.com/WeakAuras/WeakAuras2/issues/4938 is probably the same issue and a far better description of the problem.

Yeah probably, sorry I didn't know exactly what info you needed/your familiarity with the item etc and was trying to hastily write a response in between pulls of mythic Fyrakk lol.
