### ISSUE TITLE
Glow External Element not working properly with default Blizzard unit frames

### ISSUE THREAD

**Issue by truth76** [WeakAuras/WeakAuras2#5375]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Created a weakaura to track atonement on party members. The weakaura should begin glowing the corresponding frame when atonement is applied, and should stop glowing when atonement falls off. However, when using default blizzard frames it would not start glowing until either my mouse moves into or out of the unit frames, or until a buff is applied or falls off of any party member.

https://github.com/user-attachments/assets/9eddc978-c001-4a19-a25b-42808bd426e0

### WeakAuras Version

5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Weakaura attached below. While using default Blizzard unit frames, apply atonement to party members without moving your mouse into or out of the frame. The glow will not start unless another buff is applied or falls off. Apply atonement then move your mouse into or out of the frame, and the glow will start once the mouse enters or leaves the frame.

### Last Good Version

unsure what version, but it was working about 6-8 months ago (Dragonflight Season 3)

### Export String

```Text
!WA:2!1rvWUTTrq0iOdgGOiWrj1nonhesbspuedhb0u0lfquqQ2TYsku0XPNOwYDP42UC3T7U0s0hf6HCwhAVRZTx4Nq)cie6xG)e8xqNLui2OOwx0m7o7mV3BMHng0kTfUf(dFPsKzyuorn(C)HNoQ)wuMjrOglnubx7uGPAjdL7twAA5SvNGWIf)044ynX88huG4rqWteuUjSx)r(99KTVZlcIfQuKjqgyOPKDEnK7hLPnIuBeNlXidXJCjHBUgkTacGgDbfBsC7cUkuufqEJN2GuMFFZCMyrqKGju)qt4xrLFDqU6eXI6a0rigzsZxFuNRR8JvKFnJWJYN084J6CZUZqaMm5sY6ZhDQ)aVUN1xHfb2lNDDMMeCBTMvNwRqPpCDLT9HQU9MMaN5s5uJtym8No5YYNu(PxNqXKaeJvLe9SY9lFu5bjLF2S1qjQ5Fs5HEtOljSvgfD(CIs)WxQ2z(HNyrWzitucGGmUjznktH4aK1pBDxJGtsbjtjwWhZz5ZUwNfwjItuKy6sVPt6pCyrKineG3zcmPWkoNqNNq0MnysywCSVLbN0F4KbNpCJ96EmiT6zUwQ5zlxNpM2Pq80Lfb96o1pyQFxp)I5WOJSgCToU0j8ecIzsKp(oNpgkacAIT(UI0BPsRJLp(oU3g0kTKWyNI1okG8JaUw1h((BtyY2Qhs0tb4oMxH6USfOCTxL044MbDcpjmQKVgIVwmDKpYoHCjXV23Qh)5dKV4(Nutf4aauKzYxE)bXiZrr5bXmHqLSwtyX1lcUJ99hFMBSGBK7pqrVQ9BZqyiDO2((Baf1Jm3ot)SdkF1wWnef9lwrJJDzce(DRTZECq2vjHgyoMBoWlnJzOoUGafDq5p64fXqAT1YvtVIynwzR3uW5WDBPVVElT5gvv5SDBxdWc1Y6lACdawIIJyVdg9Gi(d5N))s2AdplNXYV4(1dPIerTjQ5gywHGR2I)Tpz1cHcFHcjxDXodVB3Fv)mSkqJZDh2FG)gJi6YAS80g)vXlOy5t)4OEBFOgkD7j2EB7oDYO4IWEXFl)QEzYR6wuTop1yL5M3u)DPb2JS8oCApV(9hPY3X8WibpMo3r(v3pBW5WefnkWKOiWygdNxuRR9QaFJgnAUbsdMU7dLuE97bpN1ioT28nLpCq5RC5aj(BcsBbiHp3KS3wmSFzJO(djAInx6v2ySiUK5MIOC4TLSY09k5LIsjy(8)7jT0HF9rV(Bo64wx(pV)Fp
```

**Comment by mrbuds** [comment]
I can repro the problem in follower dungeon, i think the problem happen only with the "AutoCast Shine" glow


https://github.com/user-attachments/assets/3723f6cf-b550-42cc-a7b0-b1c1ae5f82ff


https://github.com/user-attachments/assets/36abf19d-b413-4fa9-9bd8-b13162c3df75


https://github.com/user-attachments/assets/48d36821-78a1-47ca-9867-18e7e9a26375


https://github.com/user-attachments/assets/c776fab9-9b0f-4620-87c7-01f8023ec298

**Comment by InfusOnWoW** [comment]
I can't reproduce that problem, all glows work for me. I did use blizzards's unit frames in the "raid" display, and AutoCast Shine just works, like the other glows too. I do not have any clue why it works for me though, nor any clue what might break it.

**Comment by mrbuds** [comment]
I tried to make a short clip but had to disable SUF & Grid2 and switch class & spec to somewhat reproduce https://www.twitch.tv/videos/2245426662
near end of video you can see an abnormal delay before the glow start to show

**Comment by mrbuds** [comment]
i used this aura
```
!WA:2!1rvZUTTrq4iiGguH(JRSHHDsrHGlqGdArIJAqqZLciQkf7czlvk644(dOwYDP42UC3T7UuY0hf6HCwx7nDU9cp0hG(eqy0Na)i4NGolPrTrrTUOzMDMzNVp(TtT(ntAIBIF7UkrQHr5e1WJ9gCWr9uNnmkstm1uzxBKJ4HXc1ibLBc627iVEUYwyQwYqzEKZm(rcvcY4l9n0eY1E1KRfMQnIeBghlXidXLmJWnxIsHOidn8ek2e70bCvOqdvW1VWvBqkZFUAktm3puWeQVPo8lV0VkjhDSyEvc6qeJmQ(ZEsBfw4Bdn5QYdIuiyqmzsYYJp6aV(UDoSxq14i3sQaCS7o22SZN36veJhm17(4hF51Ls(LucpmBu99Es7lt1e)BgMjllTTnw1P74yG2wc3CvNNunuwUuVTdLtnncIG)0XZkAgFzmft8rmwz70tk(WI1kwVyJITMu8W4ITDhrpJWwyu0Ptjk9h8i11MVDd7qCiYegddrk3eVeLQqCaH6he8Sx(8V4lF(fj2Jj6XaMgYxzHwh2CuM(sDAqjRpsrION5oEuVbdYdfjbWuEOatYT5UpDkuSzfMeKgf5zr3(9gmQ)XdkBvxMaG0ehlSDT3D7)TTJH8PNL73TZyp)XEDC9YNcckz1K2CVI3nyFcIzIZtUban3tU(TChcxhc0an)k563Q4BcVqljm2byDdfWehbaFILsE1n5g7wshnuI58HCw2eNuG(DLGwkBjCEft2q(rwj0mIxLVf))(9Kp8)vkxz4Av0y5JUB1oJmffM5hXecv8I5cf(efsU4KRnCIeCJCT(k65T(2uegGeQLN3kGaDjtTA(hSzXtVaCdqH)Sf(CSdtGWVEPv6XbwwfhyaDo3SPBskZqB4a8r4Mfh2WnKH0ARLJMEoXASWEFJbNTd0IuvijGMifkZf6yewm)nvpPRVsvE52p1ogauxbpjikoI9Aq7bh8BlrCQ9rQG)II3VFXtD4Gg4ViinzSrr4tnX3)cmifSzu9EqtcfCSEHnhBFlo1jbr5qTfNw8D3V47l(HIFem)K)BKvGcIGlxg8RVN8tVBQwQiHu70v)A0CAfA(47j35URkrG9H5KmX9M9jQFcEXsJYCg0RV3kJiCwfS3Q2FKVdfl3QJbGBcW5TSlhu6wJSsPwTBNsX5bDJEj)8UPYZ7KxUPbOe4Z66xvTNSVnujdSXfWUoiYqz52TgbadfrN2yPMWIkxNw8oYp7UhDCgiRPH(MyfbEiYWz5vaVBjsQvRw9vwsNw1(CkVQEWRr(TAB7eHOPU9xtM1C2F)M)j
```

**Comment by InfusOnWoW** [comment]
I could reproduce something that looks similar to your twitch stream, there's a one frame delay on applying the glow, which is fixed by: https://github.com/Stanzilla/LibCustomGlow/pull/26

But that doesn't appear to be the same issue as the original issue, nor your first video.

It might be that your trouble in re-reproducing the issue was due to the game behaving differently, and that the original issue is now fixed.

**Comment by InfusOnWoW** [comment]
@truth76 can you also retest? With my current theory, the current release the glow will look a bit slow to apply, but should not depend on mouse highlighting the frame or not.

**Comment by truth76** [comment]
Updated to the current alpha build of WA and the problem still exists for me, but as mrbuds said, it only happens with the autocast shine glow, and changing it to a different type of glow works fine. When using the autocast shine, it still depends on the mouse or on other buffs falling off/being applied.

https://github.com/user-attachments/assets/1a1a697c-7fe6-4da3-b9a3-454c66ef856f

https://github.com/user-attachments/assets/6508b3c0-2f46-4b29-b493-f0ab433dda96

**Comment by InfusOnWoW** [comment]
@truth76 This is very strange, I can't reproduce that. And I think buds is also no longer able to reproduce it.

Can you check the last release? It might behave differently since the LibCustomGlow has a small change, even though it shouldn't fix your issue. If it behaves differently that might hint at what the problem is.

Also are your tests with all other addons disabled?

**Comment by truth76** [comment]
The issue was happening even with all other addons disabled, but it seems to be working as expected now in 5.17.1

https://github.com/user-attachments/assets/5ed89d55-22ab-4c0e-8964-b4d15e9c83bc

**Comment by InfusOnWoW** [comment]
Well, that was not suppose to fix it, but I'll take it.
