### ISSUE TITLE
Progress based sub region not working when source is Automatic

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAuras2#5752]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues.

### Description

I've made several auras that have a progress texture to show a buffs duration and then cooldown by using the automatic source selection.  This isn't working anymore.  It now shows as zero when automatic is selected as the source.  Oddly enough, if I pick trigger two, remaining duration, it works like automatic did.

### WeakAuras Version

5.19.5-10-gf2f1f68

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
N/A
```

### Reproduction Steps

Make a two trigger aura
Add a progress texture sub region
See how nothing shows

### Last Good Version

5.19.5-1-ged0c109

### Export String

```Text
!WA:2!nA1tpTXru84sLOYksfmeieuLCYHO8NgumuOnrQvY2yxCRb7URbIAHApE3zTNM1ZmDMzbCpIYboZhGEWx6LQEGpcCR3gz1pb5JaFc6B2D9FjvQ(YU77)VF)EZBCIIP6KYnL7flloRINNeRsi6g)spbUfHrR1LJTWD4QU9umNtWcji8(j(RfVuI99QYiuvZ8f2RwbRC(mKBXMkKpMQwYQtGVIKmNKJDwsNmPLJpsknVLts(nS5fbYrbbtULLuHeQKn9iuISDYCWdvYZvcsRwq((9hlIF9I5fq489l5(aRnZS5gBCUBGazIXJYS57LbnXNaPUQa7roZYUAHYL75IBg45zAcXofkxT4(LZPmDecCCDran0dlfPd29QajUEC8ByfQOxEwNMiv6YSwddVnepYz9RNpRDT627NpFbB7RnHl0vIR8bn3yJnE1MFz)HXBpuhC7ZJdTm57dvWceo49HoTHff0ltMla(Oj3h1fl6nsT(53a2x4maSSJlUldOXisYhRx4I5Suau(2COaftVQvyEcZbY)uuxPseGBO)m9l5PmcjTOmbMbmPG4IBWN3iSfMIfeh72StRqB0FIp7jHhzddL(z6N3xGr(2dARp5V3v)4g608vYZy(UStPPRkyTeyPm9tcT6P6LsL5s5yoWxWKsSPJgHpqtbcdBKg6v0pqV2s6n1BDLlr(lbuyq5e86iAxEkNaPI1Pwu)dedXHVNxOfm6tIHLNMmn8tGvbcA6bc)PmhNgrDttzQ0deTXXpnntm8Z1pojM6YNhfMV4CSlZf)N3X6uIRQ97U7nWapwqr(heDu4p6dWEBMOcpCwo5LikPt4m5w6pT41yKeBReyAlv7z1RMJYO4(dMARBgffsSdJ6kp3yQzqvxmxheHwuxaCqxu)T6D0LGNZnTKhrC5lpeTTdAgDInDnSuDfI6avv45t9Sx5jaigQdKcnZnrQkAezYxt78wfkS36be3RkyFG1oCUZU)GvtOQ8iTs2dg8TcdS81xSmpLpHIrIA4ZaWfNN5ZeF3mWp(9NqrfbboRe2L92PIvPFSYE1Yw2s6aBhMPNz1rDEuTXxCchJFWFDjdo7HCWhL11TcvE0Hy0BZAoND0Uyxc6OylLhz)RbibUEXaF)dBtuy(YteXTXsKYG442XOs9oaLMd8bnqG591ZwUmFHjCDFjwu)Se87nHulwuJLqVkFoaDIuQIu(EEmHyhEc(zF(D(i(st4Eoy)ORzOYkx5c7T9u9)bejPPpCUCYkjVGXR3T6h)Y1(Im6SzNQIouG4MiYxmF5S7wTwLCLZM)7ZU92LQv6GcFOMQBc(kti1GSdBSMTXKwTvz)qfXzrfX1Xi3awCsl3LiemrByEzjhIWjW)w9N(WzULUbC)38)N7ZdrWhx3UdJPAxpht4If63a1Z9Mk2JdG8fNw5WXy9pRRd0AkGwhytmXYxzkNSnxALL2YhNq7eYZtBXytE8vNs3e4n)(tPD4mIgFRojgBntbt7wEFMZBpLiHXNLNs1OH2J0hRP6z1(z)WGumbFl2Pe1C7p0kth6cu3qy4DlDXQxhTEoC5ImbFb4dEhMjXJ3sZps8aoVW)nNBdgVBOXJ49sW2Pkq9a3wkpkRWXcd7SzHuVHc7b5Qkgo)rvZ0lQKSyNkFOP5Vo8FBeRnr)iTWeqqhQ8HJxAdgvVmC7PfqJFTE1(WKXitIiEdCEZiHJTuCXrshByqqIHsdhoxmIr8X7eEQlXqrM0EO5ANe85htuSzx3efE3KFEFcVbqN9hE1JzT(5dwePpC2BgLJO4P9F3D7zU2HeDR1veQhte5CslKpVnAMusEQnxlZRwBZxK5LVOL36Ez826RsDY)8M)9p
```

### Bisector Report

```Text

```

**Comment by InfusOnWoW** [comment]
This should be fixed in the next release.

**Comment by Crelam** [comment]
Sorry to be a bother, but is that the next full release?  I only ask because I just checked with version 5.19.5-19-g4ad842b and the issue still persists.  Unless I'm doing something wrong here. 😅

**Comment by InfusOnWoW** [comment]
I'll check again then

**Comment by Crelam** [comment]
Confirmed as fixed in 5.19.5-35-gba74644.  Thank you for your service.
